# Generated by Django 5.1.6 on 2025-03-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50, null=True)),
                ('approve', models.BooleanField(default=False, null=True)),
                ('reject', models.BooleanField(default=False, null=True)),
                ('c_id', models.CharField(max_length=50, null=True)),
                ('login', models.BooleanField(default=False, null=True)),
                ('logout', models.BooleanField(default=False, null=True)),
                ('ihdone', models.BooleanField(default=False, null=True)),
                ('badone', models.BooleanField(default=False, null=True)),
                ('abdone', models.BooleanField(default=False, null=True)),
                ('final', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.PositiveBigIntegerField(null=True)),
                ('height', models.PositiveBigIntegerField(null=True)),
                ('width', models.PositiveBigIntegerField(null=True)),
                ('medical_condition', models.CharField(max_length=50)),
                ('prosthetics_type', models.CharField(max_length=50)),
                ('Integrate_Hub_Report', models.FileField(null=True, upload_to='Integrate_Hub_Report/')),
                ('ihdone1', models.BooleanField(default=False, null=True)),
                ('Material_Composition', models.CharField(max_length=50, null=True)),
                ('Age_of_Application_years', models.PositiveBigIntegerField(null=True)),
                ('Usage_Frequency_times_day', models.PositiveBigIntegerField(null=True)),
                ('Physical_Activity_Level', models.PositiveBigIntegerField(null=True)),
                ('Impact_Resistance', models.PositiveBigIntegerField(null=True)),
                ('Wear_Resistance', models.PositiveBigIntegerField(null=True)),
                ('Corrosion_Resistance', models.PositiveBigIntegerField(null=True)),
                ('Temperature_Resistance', models.PositiveBigIntegerField(null=True)),
                ('Integrity', models.PositiveBigIntegerField(null=True)),
                ('Weight', models.CharField(max_length=50, null=True)),
                ('Characteristics', models.CharField(max_length=50, null=True)),
                ('Integrity_Level_Pre', models.FloatField(null=True)),
                ('badone2', models.BooleanField(default=False, null=True)),
                ('Actuation_Mechanism', models.CharField(max_length=250, null=True)),
                ('Biocompatibility_Factors', models.CharField(max_length=250, null=True)),
                ('Typical_Force_Output_N', models.CharField(max_length=250, null=True)),
                ('Specific_Surface_Area', models.CharField(max_length=250, null=True)),
                ('Control_Response_Time', models.CharField(max_length=250, null=True)),
                ('Energy_Density', models.CharField(max_length=250, null=True)),
                ('Weight_Actubio', models.CharField(max_length=250, null=True)),
                ('abdone3', models.BooleanField(default=False, null=True)),
                ('bp_final_report', models.FileField(null=True, upload_to='BP_Final_Report/')),
                ('finalreportview', models.BooleanField(default=False, null=True)),
                ('finalreportapprove', models.BooleanField(default=False, null=True)),
                ('finalreportreject', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
